#! /bin/sh

base=`pwd`

cd Abp && vl2mv abp.v && cd $base
cd Am2901 && vl2mv am2901.v && cd $base
cd Am2910 && vl2mv am2910.v && cd $base
cd Amp && vl2mv amp.v && cd $base
cd Arbiter && vl2mv arbiter.v && cd $base
cd Arbiter && vl2mv arbiter_bug.v && cd $base
cd Arbiter && vl2mv arbiter_le.v && cd $base
cd Bakery && vl2mv bakery.v && cd $base
cd Bakery && vl2mv eisenberg.v && cd $base
cd Bakery && vl2mv good_bakery.v && cd $base
cd Bakery && vl2mv bakery_ot.v && cd $base
cd Bakery && vl2mv atom_bakery.v && cd $base
cd Bakery && vl2mv synch_bakery.v && cd $base
cd Barrel && vl2mv barrel4.v && cd $base
cd Barrier && vl2mv barrier.v && cd $base
cd Blackjack && vl2mv blackjack.v && cd $base
cd Bpb && vl2mv bpbs.v && cd $base
cd BufAl && vl2mv bufferAlloc.v && cd $base
cd BufAl && vl2mv buf_bug.v && cd $base
cd CRC && vl2mv vcrc32_8.v && cd $base
cd Cex && vl2mv cex.v && cd $base
cd Cgw && vl2mv cgw.v && cd $base
cd Chameleon && vl2mv chameleon.v && cd $base
cd Coherence && vl2mv coherence.v && cd $base
cd Cordic && vl2mv vcordic.v && cd $base
cd Counter && vl2mv counter.v && cd $base
cd Crd && vl2mv crd.v && cd $base
cd Ctlp && vl2mv ctlp3.v && cd $base
cd Cube && vl2mv cube.v && cd $base
cd Cube && vl2mv cubeAbs.v && cd $base
cd Cups && vl2mv cups.v && cd $base
cd DAIO && vl2mv daio_receiver.v && cd $base
cd Dcnew && vl2mv dcnew.v && cd $base
cd Dekker && vl2mv dekker.v && cd $base
cd EL2Omega && vl2mv el2Omega.v && cd $base
cd Elevator && vl2mv ely1-3.v && cd $base
cd Elevator && vl2mv elevator1-4.v && cd $base
cd Ethernet && vl2mv ethernet.define.112.v && cd $base
cd Ethernet && vl2mv ethernet.define.212.v && cd $base
cd Ethernet && vl2mv ethernet.define.312.v && cd $base
cd Ethernet && vl2mv ethernet.define.412.v && cd $base
cd ExampleS && vl2mv exampleS.v && cd $base
cd FIFOs && vl2mv FIFOs.v && cd $base
cd FPMult && vl2mv FPMult.v && cd $base
cd FPMult && vl2mv FPMultFixed.v && cd $base
cd FPMult && vl2mv FPMultLTL1.v && cd $base
cd Feistel && vl2mv sfeistel.v && cd $base
cd Field && vl2mv field5.v && cd $base
cd FourByFour && vl2mv two.v && cd $base
cd FourByFour && vl2mv twoAll.v && cd $base
cd FourByFour && vl2mv luckySeven.v && cd $base
cd FourByFour && vl2mv luckySevenONE.v && cd $base
cd Gcd && vl2mv gcd.v && cd $base
cd Gcd && vl2mv gcdLTL2.v && cd $base
cd Gigamax && vl2mv gigamax.v && cd $base
cd Gray && vl2mv gray.v && cd $base
cd Hanoi && vl2mv hanoi.v && cd $base
cd Hanoi && vl2mv newHanoi.v && cd $base
cd Heap && vl2mv heap.v && cd $base
cd HourGlass && vl2mv ghg.v && cd $base
cd Huffman && vl2mv huff.v && cd $base
cd ITC99/b01 && vl2mv b01.v && cd $base
cd ITC99/b02 && vl2mv b02.v && cd $base
cd ITC99/b03 && vl2mv b03.v && cd $base
cd ITC99/b04 && vl2mv b04.v && cd $base
cd ITC99/b05 && vl2mv b05.v && cd $base
cd ITC99/b06 && vl2mv b06.v && cd $base
cd ITC99/b07 && vl2mv b07.v && cd $base
cd ITC99/b08 && vl2mv b08.v && cd $base
cd ITC99/b09 && vl2mv b09.v && cd $base
cd ITC99/b10 && vl2mv b10.v && cd $base
cd ITC99/b11 && vl2mv b11.v && cd $base
cd ITC99/b12 && vl2mv b12.v && cd $base
cd ITC99/b12 && vl2mv b12abs.v && cd $base
cd ITC99/b12 && vl2mv b12abs2.v && cd $base
cd ITC99/b13 && vl2mv b13.v && cd $base
cd Ibuf && vl2mv ibuf.v && cd $base
cd Jam && vl2mv jam.v && cd $base
cd Lock && vl2mv lock.v && cd $base
cd Lock && vl2mv lockAbs.v && cd $base
cd Matrix && vl2mv matrix.v && cd $base
cd Matrix && vl2mv matrix_bug.v && cd $base
cd Microwave && vl2mv microwave.v && cd $base
cd Miim && vl2mv vMiim.v && cd $base
cd MinMax && vl2mv minMax.v && cd $base
cd MinMax && vl2mv minMaxR.v && cd $base
cd MinMax && vl2mv product.v && cd $base
cd Needham && vl2mv ns1.v && cd $base
cd Needham && vl2mv ns2.v && cd $base
cd Needham && vl2mv ns3.v && cd $base
cd Nim && vl2mv all.v && cd $base
cd NullModem && vl2mv nullModem.v && cd $base
cd NullModem && vl2mv nullModemLTL1.v && cd $base
cd Palu && vl2mv palu.v && cd $base
cd Palu && vl2mv paluLTL1.v && cd $base
cd Param/Arbiter && vl2mv arbiter3.v && cd $base
cd Param/Arbiter && vl2mv arbiter5.v && cd $base
cd Param/Arbiter && vl2mv arbiter7.v && cd $base
cd Param/Arbiter && vl2mv arbiter9.v && cd $base
cd Param/Bakery && vl2mv bakery1.v && cd $base
cd Param/Bakery && vl2mv bakery2.v && cd $base
cd Param/Bakery && vl2mv bakery3.v && cd $base
cd Param/Bakery && vl2mv bakery4.v && cd $base
cd Param/Bakery && vl2mv bakery5.v && cd $base
cd Param/Bakery && vl2mv bakery6.v && cd $base
cd Param/Bakery && vl2mv bakery7.v && cd $base
cd Param/Bakery && vl2mv bakery8.v && cd $base
cd Param/Bakery && vl2mv bakery9.v && cd $base
cd Param/Drop && vl2mv drop4.v && cd $base
cd Param/Drop && vl2mv drop8.v && cd $base
cd Param/Drop && vl2mv drop16.v && cd $base
cd Param/Drop && vl2mv drop32.v && cd $base
cd Param/Drop && vl2mv drop64.v && cd $base
cd Param/Drop && vl2mv drop128.v && cd $base
cd Param/Drop && vl2mv drop256.v && cd $base
cd Param/Elevator && vl2mv elevator1-3.v && cd $base
cd Param/Elevator && vl2mv elevator1-4.v && cd $base
cd Param/Elevator && vl2mv elevator1-5.v && cd $base
cd Param/Elevator && vl2mv elevator1-6.v && cd $base
cd Param/Elevator && vl2mv elevator2-3.v && cd $base
cd Param/Elevator && vl2mv elevator3-3.v && cd $base
cd Param/Hrglass && vl2mv hrglass8.v && cd $base
cd Param/Hrglass && vl2mv hrglass10.v && cd $base
cd Param/Hrglass && vl2mv hrglass12.v && cd $base
cd Param/Hrglass && vl2mv hrglass14.v && cd $base
cd Param/Hrglass && vl2mv hrglass16.v && cd $base
cd Param/Lock && vl2mv lock5.v && cd $base
cd Param/Lock && vl2mv lock6.v && cd $base
cd Param/Lock && vl2mv lock7.v && cd $base
cd Param/Lock && vl2mv lock10.v && cd $base
cd Param/MinMax && vl2mv minMax8.v && cd $base
cd Param/MinMax && vl2mv minMax16.v && cd $base
cd Param/MinMax && vl2mv minMax32.v && cd $base
cd Param/MinMax && vl2mv minMax64.v && cd $base
cd Param/MinMax && vl2mv minMax128.v && cd $base
cd Param/Philo && vl2mv philo4.v && cd $base
cd Param/Philo && vl2mv philo8.v && cd $base
cd Param/Philo && vl2mv philo16.v && cd $base
cd Param/Philo && vl2mv philo32.v && cd $base
cd Param/Philo && vl2mv philo64.v && cd $base
cd Param/Philo && vl2mv philo128.v && cd $base
cd Param/Philo && vl2mv philo256.v && cd $base
cd Param/TreeArb && vl2mv treearb4.v && cd $base
cd Param/TreeArb && vl2mv treearb8.v && cd $base
cd Param/TreeArb && vl2mv treearb12.v && cd $base
cd Param/TreeArb && vl2mv treearb16.v && cd $base
cd Param/Vending && vl2mv vending3.v && cd $base
cd Param/Vending && vl2mv vending4.v && cd $base
cd Param/Vending && vl2mv vending5.v && cd $base
cd Param/Vending && vl2mv vending6.v && cd $base
cd Param/Vending && vl2mv vending7.v && cd $base
cd Param/Vending && vl2mv vending8.v && cd $base
cd Pathfinder && vl2mv pf.v && cd $base
cd Peterson && vl2mv peterson.v && cd $base
cd Philo && vl2mv philo.v && cd $base
cd Philo && vl2mv nosel.v && cd $base
cd Philo && vl2mv philo4.v && cd $base
cd Philo && vl2mv drop4.v && cd $base
cd PicoJava/biu && vl2mv biu.v && cd $base
cd PicoJava/icu && vl2mv ibuf_ctl.v && cd $base
cd PicoJava/icu && vl2mv ic_cntl.v && cd $base
cd PicoJava/icu && vl2mv icctl.v && cd $base
cd PicoJava/icu && vl2mv icctl_env.v && cd $base
cd PingPongN && vl2mv ping_pong_new.v && cd $base
cd Pong && vl2mv ball.v && cd $base
cd ProdCell && vl2mv prodcell.v && cd $base
cd ProdCell && vl2mv prodcellLTL2.v && cd $base
cd RCU && vl2mv rcu.v && cd $base
cd Rcnum && vl2mv rcnum16.v && cd $base
cd Rcnum && vl2mv rcnum25.v && cd $base
cd Relinit && vl2mv relinit.v && cd $base
cd ReqAck && vl2mv reqAck.v && cd $base
cd ReqAck && vl2mv reqAckRed.v && cd $base
cd Reset && vl2mv reset.v && cd $base
cd Rether && vl2mv retherRTF.v && cd $base
cd Rether && vl2mv retherSQO.v && cd $base
cd Rgraph && vl2mv rgraph.v && cd $base
cd Rotate && vl2mv rotate4.v && cd $base
cd Rotate && vl2mv rotate32.v && cd $base
cd Rrobin && vl2mv rrobin.v && cd $base
cd Rrobin && vl2mv rrobinltl.v && cd $base
cd Sampleq && vl2mv twoFifo1.v && cd $base
cd Sampleq && vl2mv twoQ.v && cd $base
cd Scheduler && vl2mv scheduler.v && cd $base
cd Segments && vl2mv sg1.v && cd $base
cd Short && vl2mv short.v && cd $base
cd Silver-bcu && vl2mv bcuvis32.v && cd $base
cd Silver-exu && vl2mv Bcc.v && cd $base
cd Silver-exu && vl2mv IntArith.v && cd $base
cd Silver-exu && vl2mv IntLogic.v && cd $base
cd Silver-exu && vl2mv Jmp.v && cd $base
cd Silver-exu && vl2mv Mem.v && cd $base
cd Silver-fru && vl2mv fru32.v && cd $base
cd Silver-idu && vl2mv idu32.v && cd $base
cd Silver-mau && vl2mv controlvis.v && cd $base
cd Silver-pcu && vl2mv pcuv.v && cd $base
cd Slider && vl2mv slider.v && cd $base
cd Smult && vl2mv spm.v && cd $base
cd Soap && vl2mv soap.v && cd $base
cd Soap && vl2mv shampoo.v && cd $base
cd Soap && vl2mv soapLTL1.v && cd $base
cd Soap && vl2mv soapLTL3.v && cd $base
cd Soap && vl2mv soapLTL3.v && cd $base
cd Soap && vl2mv soapLTL4.v && cd $base
cd Solitaire && vl2mv solitaireVL.v && cd $base
cd Spinner && vl2mv spinner4.v && cd $base
cd Spinner && vl2mv spinner32.v && cd $base
cd Sppinterf && vl2mv sppinterf.v && cd $base
cd Sppinterf && vl2mv sppint2.v && cd $base
cd Sppinterf && vl2mv product.v && cd $base
cd StrLTL/bakery && vl2mv bak_otLTLM1.v && cd $base
cd StrLTL/bakery && vl2mv bak_otLTLM2.v && cd $base
cd StrLTL/bakery && vl2mv bak_otLTLM3.v && cd $base
cd StrLTL/bakery && vl2mv bak_otLTLM4.v && cd $base
cd StrLTL/bakery && vl2mv bak_otLTLM5.v && cd $base
cd StrLTL/eisenberg && vl2mv eisenbergLTLM1.v && cd $base
cd StrLTL/eisenberg && vl2mv eisenbergLTLM2.v && cd $base
cd StrLTL/ele && vl2mv eleLTLM1.v && cd $base
cd StrLTL/nullmodem && vl2mv nullmodemLTLM1.v && cd $base
cd StrLTL/peterson && vl2mv mppLTLM1.v && cd $base
cd StrLTL/ctlp3 && vl2mv ctlp3LTLM1.v && cd $base
cd StrLTL/ctlp3 && vl2mv ctlp3LTLM2.v && cd $base
cd StrLTL/ctlp3 && vl2mv ctlp3LTLM3.v && cd $base
cd StrLTL/soap && vl2mv soapLTLM1.v && cd $base
cd StrLTL/soap && vl2mv soapLTLM2.v && cd $base
cd StrLTL/soap && vl2mv soapLTLM3.v && cd $base
cd StrLTL/twoq && vl2mv twoqLTLM1.v && cd $base
cd StrLTL/twoq && vl2mv twoqLTLM2.v && cd $base
cd Swap && vl2mv swap.v && cd $base
cd SyncArb && vl2mv syncarb.v && cd $base
cd Tcp && vl2mv tcp.v && cd $base
cd TicTacToe && vl2mv ticTacToe.v && cd $base
cd Timeout && vl2mv timeout.v && cd $base
cd Tlc && vl2mv tlc.v && cd $base
cd TreeArb && vl2mv 4-arbit.v && cd $base
cd TreeArb && vl2mv 8-arbit.v && cd $base
cd TreeArb && vl2mv eight.v && cd $base
cd TreeArb && vl2mv simple8.v && cd $base
cd Unidec && vl2mv unidec.v && cd $base
cd Unidec && vl2mv ex2.v && cd $base
cd Unidec && vl2mv ex3.v && cd $base
cd UsbPhy && vl2mv usb_phy.v && cd $base
cd Vending && vl2mv vending.v && cd $base
cd Viper && vl2mv viper.v && cd $base
cd Vlunc && vl2mv vlunc.v && cd $base
cd Vsa16 && vl2mv vsa16a.v && cd $base
cd VsaR && vl2mv vsaR.v && cd $base
cd s1269 && vl2mv s1269b.v && cd $base
